language: node_js

node_js:
    - node

cache:
    - npm

install:
    - npm install

before_script:
    - npm install -g codecov

script:
    - npm run lint
    - npm run build
    - npm run tests
    - npm run tests:coverage
    - npm run performance
    - npx codecov