language: node_js

node_js:
    - node

cache:
    - npm

install:
    - npm install

before_script:
    - npm install coveralls --no-save

script:
    - npm run lint
    - npm run build
    - npm run tests
    - npm run performance